### ISSUE TITLE
Todo to go public!

### ISSUE THREAD

**Issue by jlperla** [jlperla/PerlaTonettiWaugh.jl#309]
- [x] Modify the algorithm document for the fixed point
- [x] Make sure `full_transition_dynamics.ipynb` and `.jmd` are very clean, executed cleanly without warnings, etc.
- [x] Create a `develop.md` or something like that which would have most of the current README
- [x] Create the REAME.md to be minimalist as a user, not modifying it.
  - How to get the path of the package?  Or maybe activating it? `activate PerlaTonettiWaugh`
- [x] Remove any notebooks that are not essential and move to the graveyard - compare_steady_state - delete solve-transition.pdf (Resolved by 75bc52c and bd880ac)
- [x] Maybe move `graveyard` inside of `test` (Resolved by 1f475df)
- [x] Squash all commits
- [ ] Delete all issues, or just turn off issues entirely?
- [ ] Get the packagecompiler/binder working.
- [x] Fix up the initial conditions for the solution and the coarse solution to have the known value (Resolved by 43fe744)
- [x] Delete all caches in the `data` folder except for the coarse and full grids. (Resolved by edd7ea5)
- [x] Tag SDO.jl and generate documents/notebooks for both `dev` and the tag
